version: "3"

services:
  web:
    image: web
    links:
      - db
    environment:
      - APP_DEBUG=True
      - DB_DRIVER=postgres
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - KEY=9CGsQWriKGGprcjU5XlHchWdwRxEYiwiesa_5Rd5XhA=
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 5672:5672
  lb:
    image: dockercloud/haproxy
    links:
      - web
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - /var/lib/postgresql/data
