version: "3"

services:
  web:
    image: web
    environment:
      - APP_DEBUG=True
      - DB_DRIVER=postgres
      - DB_DATABASE=postgres
    links:
      - db
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 5672:5672
  lb:
    image: dockercloud/haproxy
    links:
      - web
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  db:
    image: postgres
    restart: always
    links:
      - web
    ports:
      - '5432:5432'
