FROM python:3.6.6

RUN pip install masonite-cli
RUN mkdir -p /code/releases

COPY ./release /code/releases/$release
COPY ./venv /code/releases/$release/venv
WORKDIR /code/releases/$release
RUN pip install gunicorn

EXPOSE 80

CMD source venv/bin/activate && gunicorn --bind 0.0.0.0:80 wsgi 
