FROM python:3.6.6

RUN pip install masonite-cli gunicorn
RUN mkdir -p /code/releases

COPY ./release/requirements.txt /code/releases/requirements.txt
WORKDIR /code/releases/
RUN pip install -r requirements.txt
COPY ./release /code/releases

EXPOSE 80

CMD gunicorn --bind 0.0.0.0:80 wsgi:application
