FROM python:3.6.6

RUN pip install masonite-cli
RUN mkdir -p /code/releases

COPY ./release /code/releases/$release
WORKDIR /code/releases/$release
RUN pip install -r requirements.txt
RUN pip install gunicorn

EXPOSE 80

CMD gunicorn --bind 0.0.0.0:80 wsgi 
